apiVersion: v1
kind: ConfigMap
metadata:
  name: sample-python-app-cm
data:
  # property-like keys'; each key maps to a simple value
  container_port: "8000"
  host_name: "foo.bar.com"
  # file like keys
  game.properties: |
    enemy.types=aliens,monsters
    player.maximum-lives=5    
  user-interface.properties: |
    color.good=purple
    color.bad=yellow
    allow.textmode=true    
    
